name: ${project.name}
version: ${project.version}
description: Library of useful classes for Bukkit plugin development purposes
depend: []
softdepend: []
author: Stealth2800
website: http://stealthyone.com/bukkit
main: com.stealthyone.mcb.stbukkitlib.StBukkitLib
commands:
  stbukkitlib:
    aliases: [stbl]