name: ${project.name}
version: ${project.version}
description: Testing plugin for StBukkitLib
depend: []
softdepend: []
author: Stealth2800
website: http://stealthyone.com/
main: com.stealthyone.mcb.stbukkitlib.StBukkitLib
commands:
  stbukkitlib:
    aliases: [stbl]