name: ${project.name}
version: ${project.version}
description: Set of useful Bukkit-related classes
depend: []
softdepend: [WorldEdit, WorldGuard, VanishNoPacket, Vault]
author: Stealth2800
website: http://stealthyone.com/bukkit
main: com.stealthyone.mcb.stbukkitlib.StBukkitLib
commands:
  stbukkitlib:
    aliases: [stbl]